export const data = [
  {
    title: {
      name: "Book 1",
      link: "https://example.com/book1",
      topic: 1,
      lesson: 1,
    },
    category: "Fiction",
    price: 19.99,
    date: {
      date: "February 01, 2024",
      time: "11:26 AM",
    },
    author: "John Doe",
    status: "Available",
    action: "Edit",
  },
  {
    title: {
      name: "Book 2",
      link: "https://example.com/book2",
      topic: 2,
      lesson: 2,
    },
    category: "Non-Fiction",
    price: 24.99,
    date: {
      date: "February 01, 2024",
      time: "11:26 AM",
    },
    author: "Jane Smith",
    status: "Out of Stock",
    action: "Edit",
  },
  {
    title: {
      name: "Book 3",
      link: "https://example.com/book3",
      topic: 3,
      lesson: 3,
    },
    category: "Fantasy",
    price: 14.99,
    date: {
      date: "February 01, 2024",
      time: "11:26 AM",
    },
    author: "Alice Johnson",
    status: "Available",
    action: "Edit",
  },
  {
    title: {
      name: "Book 3",
      link: "https://example.com/book3",
      topic: 3,
      lesson: 3,
    },
    category: "Fantasy",
    price: 14.99,
    date: {
      date: "February 01, 2024",
      time: "11:26 AM",
    },
    author: "Alice Johnson",
    status: "Available",
    action: "Edit",
  },
  {
    title: {
      name: "Book 3",
      link: "https://example.com/book3",
      topic: 3,
      lesson: 3,
    },
    category: "Fantasy",
    price: 14.99,
    date: {
      date: "February 01, 2024",
      time: "11:26 AM",
    },
    author: "Alice Johnson",
    status: "Available",
    action: "Edit",
  },
  {
    title: {
      name: "Book 3",
      link: "https://example.com/book3",
      topic: 3,
      lesson: 3,
    },
    category: "Fantasy",
    price: 14.99,
    date: {
      date: "February 01, 2024",
      time: "11:26 AM",
    },
    author: "Alice Johnson",
    status: "Available",
    action: "Edit",
  },
  {
    title: {
      name: "Book 3",
      link: "https://example.com/book3",
      topic: 3,
      lesson: 3,
    },
    category: "Fantasy",
    price: 14.99,
    date: {
      date: "February 01, 2024",
      time: "11:26 AM",
    },
    author: "Alice Johnson",
    status: "Available",
    action: "Edit",
  },
  {
    title: {
      name: "Book 3",
      link: "https://example.com/book3",
      topic: 3,
      lesson: 3,
    },
    category: "Fantasy",
    price: 14.99,
    date: {
      date: "February 01, 2024",
      time: "11:26 AM",
    },
    author: "Alice Johnson",
    status: "Available",
    action: "Edit",
  },
  {
    title: {
      name: "Book 3",
      link: "https://example.com/book3",
      topic: 3,
      lesson: 3,
    },
    category: "Fantasy",
    price: 14.99,
    date: {
      date: "February 01, 2024",
      time: "11:26 AM",
    },
    author: "Alice Johnson",
    status: "Available",
    action: "Edit",
  },
  {
    title: {
      name: "Book 3",
      link: "https://example.com/book3",
      topic: 3,
      lesson: 3,
    },
    category: "Fantasy",
    price: 14.99,
    date: {
      date: "February 01, 2024",
      time: "11:26 AM",
    },
    author: "Alice Johnson",
    status: "Available",
    action: "Edit",
  },
  {
    title: {
      name: "Book 3",
      link: "https://example.com/book3",
      topic: 3,
      lesson: 3,
    },
    category: "Fantasy",
    price: 14.99,
    date: {
      date: "February 01, 2024",
      time: "11:26 AM",
    },
    author: "Alice Johnson",
    status: "Available",
    action: "Edit",
  },
];
